DEFAULT_PASSWORD = 'money'
DEFAULT_ADMIN_ID = 1
DEFAULT_PASWORD_ADMIN = 'mummy'
DEFAULT_PASWORDS = 'money'
DEFAULT_MINIMUM = '500'
DEFAULT_WEEK = 60
DEFAULT_PREFIX_CHANNEL = 'mummy-'
DEFAULT_FIRST_WEEK = 0

INITIAL_INVESTORS = 10
MINIMUN_KEY = 'minimun'
