# Generated by Django 2.1.7 on 2019-03-12 22:28

import uuid

from django.db import migrations, models

import mummyrest.apps.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(default='money', max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('parent', models.BigIntegerField(default=0, db_index=True)),
                ('channel', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True)),
                ('mummy_money', models.FloatField(default=0)),
                ('start_week', models.PositiveIntegerField(default=0, db_index=True)),
                ('map_tree', models.TextField(blank=True)),
                ('innocence', models.FloatField(default=0)),
                ('experience', models.FloatField(default=0)),
                ('charisma', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'member',
                'abstract': False,
            },
            managers=[
                ('objects', mummyrest.apps.members.models.MembersManager()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('leave_members', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'week',
            },
        ),
    ]
