# Generated by Django 2.1.7 on 2019-03-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mummyrest.apps.members.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('leave_members', models.PositiveIntegerField(default=0)),
                ('population', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('channel', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mummy_money', models.FloatField(default=0)),
                ('map_tree', models.TextField(blank=True)),
                ('innocence', models.FloatField(default=0)),
                ('experience', models.FloatField(default=0)),
                ('charisma', models.FloatField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('start_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week'))
            ],
            options={
                'db_table': 'member',
                'abstract': False,
            },
            managers=[
                ('objects', mummyrest.apps.members.models.MembersManager()),
            ],
        )
    ]
