# Generated by Django 2.1.7 on 2019-03-12 20:11

from django.db import migrations
from mummyrest.apps.utils import constants as const
from mummyrest.apps.members.snippets import init_member_args
from mummyrest.apps.members.models import Member


def insert_first_users(apps, schema):

    mummy = Member()
    mummy.is_staff = True
    mummy.is_superuser = True
    mummy.start_week = const.DEFAULT_FIRST_WEEK
    mummy.set_password(const.DEFAULT_PASWORD_ADMIN)
    mummy.save()

    investors = list()

    while len(investors) < const.INITIAL_INVESTORS + 1:
        investors.append(
            init_member_args(
                Member(), mummy, const.DEFAULT_FIRST_WEEK))

    Member.objects.bulk_create(investors)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_first_users),
    ]
