# Generated by Django 2.1.7 on 2019-03-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('leave_members', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'week',
            },
        ),
    ]
