# Generated by Django 2.1.7 on 2019-03-12 20:11

from django.db import migrations
from mummyrest.apps.utils import constants as const
from mummyrest.apps.members import models
from mummyrest.apps.members.snippets import init_member_args


def insert_first_users(apps, schema):

    week = models.Week.objects.create(
        id=const.DEFAULT_FIRST_WEEK,
        new_members=const.INITIAL_INVESTORS,
        population=const.INITIAL_INVESTORS)

    mummy = models.Member()
    mummy.is_staff = True
    mummy.is_superuser = True
    mummy.set_password(const.DEFAULT_PASWORD_ADMIN)
    mummy.save()

    investors = list()

    while len(investors) < const.INITIAL_INVESTORS + 1:
        investors.append(
            init_member_args(
                models.Member(), mummy, week))

    models.Member.objects.bulk_create(investors)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_first_users),
    ]
